#!/usr/bin/env bash
# Usage: init-config.sh <project-num> <owner>
# Bootstraps gh-triage.conf.sh at the repo root from your GitHub
# Project's actual fields, so you don't hand-transcribe refresh-ids.sh's
# JSON into bash yourself. Best-effort: a field or option that isn't
# named to match the Status/Priority/Target/Blocked/Decision/Active
# model (case-insensitively) is left blank with a comment instead of
# guessed - fill those in by hand, or delete the field entirely if your
# project doesn't have it (see SKILL.md).
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: init-config.sh <project-num> <owner>" >&2
  exit 1
fi

project_num="$1"
owner="$2"

repo_root=$(git rev-parse --show-toplevel)
conf="$repo_root/gh-triage.conf.sh"

if [ -f "$conf" ]; then
  echo "error: $conf already exists - remove it first to regenerate." >&2
  exit 1
fi

project_id=$(gh project view "$project_num" --owner "$owner" --format json | jq -r '.id')
fields=$(gh project field-list "$project_num" --owner "$owner" --format json)

missing=()

field_id() { # <field-name>
  echo "$fields" | jq -r --arg n "$1" \
    '.fields[] | select(.name | ascii_downcase == ($n | ascii_downcase)) | .id' \
    | head -1
}

option_id() { # <field-name> <option-name>
  echo "$fields" | jq -r --arg n "$1" --arg o "$2" \
    '.fields[] | select(.name | ascii_downcase == ($n | ascii_downcase))
     | .options[]? | select(.name | ascii_downcase == ($o | ascii_downcase)) | .id' \
    | head -1
}

emit_field() { # <var-name> <field-name>
  local id
  id=$(field_id "$2")
  if [ -z "$id" ]; then
    missing+=("$2 field")
    echo "$1=  # not found - fill in by hand, or drop if unused"
  else
    echo "$1=$id"
  fi
}

emit_option() { # <key> <field-name> <option-name>
  local id
  id=$(option_id "$2" "$3")
  if [ -z "$id" ]; then
    missing+=("$2 / $3 option")
    echo "  [$1]=  # not found"
  else
    echo "  [$1]=$id"
  fi
}

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by init-config.sh for project $project_num (owner: $owner)."
  echo "# Review before use - anything marked 'not found' didn't match by"
  echo "# name and needs a manual look at refresh-ids.sh's output, or"
  echo "# should be deleted along with its usages if this project has no"
  echo "# such field (see SKILL.md)."
  echo
  echo "PROJECT_NUM=$project_num"
  echo "OWNER=$owner"
  echo "PROJECT_ID=$project_id"
  echo
  emit_field STATUS_FIELD Status
  emit_field PRIORITY_FIELD Priority
  emit_field TARGET_FIELD Target
  emit_field BLOCKED_FIELD Blocked
  emit_field DECISION_FIELD Decision
  emit_field ACTIVE_FIELD Active
  echo
  echo "declare -A STATUS=("
  emit_option open Status Open
  emit_option "done" Status Done
  echo ")"
  echo "declare -A PRIORITY=("
  emit_option high Priority High
  emit_option medium Priority Medium
  emit_option low Priority Low
  echo ")"
  echo "declare -A TARGET=("
  emit_option now Target Now
  emit_option next Target Next
  emit_option later Target Later
  emit_option someday Target Someday
  echo ")"
  echo "declare -A BLOCKED=("
  emit_option blocked Blocked Blocked
  echo ")"
  echo "declare -A DECISION=("
  emit_option decision Decision Decision
  echo ")"
  echo "declare -A ACTIVE=("
  emit_option active Active Active
  echo ")"
} > "$conf"

echo "Wrote $conf" >&2
if [ "${#missing[@]}" -gt 0 ]; then
  echo "Not auto-resolved, review by hand:" >&2
  printf '  - %s\n' "${missing[@]}" >&2
fi
