#!/usr/bin/env bash
# Usage: init-config.sh <project-num> <owner> <project-key>
# Bootstraps gh-triage.conf.sh at the repo root from your GitHub
# Project's actual fields, so you don't hand-transcribe refresh-ids.sh's
# JSON into bash yourself. project-key is your chosen short ticket prefix
# (e.g. ETYM), used verbatim - it isn't derived from anything in the
# project. Best-effort on fields/options: anything that isn't named to
# match the Status/Type/Effort model (case-insensitively) is left blank
# with a comment instead of guessed - fill it in by hand, or delete the
# field entirely if your project doesn't have it (see SKILL.md).
set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "Usage: init-config.sh <project-num> <owner> <project-key>" >&2
  exit 1
fi

project_num="$1"
owner="$2"
project_key="$3"

repo_root=$(git rev-parse --show-toplevel)
conf="$repo_root/gh-triage.conf.sh"

if [ -f "$conf" ]; then
  echo "error: $conf already exists - remove it first to regenerate." >&2
  exit 1
fi

project_id=$(gh project view "$project_num" --owner "$owner" --format json | jq -r '.id')
fields=$(gh project field-list "$project_num" --owner "$owner" --format json)

missing=()

field_id() { # <field-name>
  echo "$fields" | jq -r --arg n "$1" \
    '.fields[] | select(.name | ascii_downcase == ($n | ascii_downcase)) | .id' \
    | head -1
}

option_id() { # <field-name> <option-name>
  echo "$fields" | jq -r --arg n "$1" --arg o "$2" \
    '.fields[] | select(.name | ascii_downcase == ($n | ascii_downcase))
     | .options[]? | select(.name | ascii_downcase == ($o | ascii_downcase)) | .id' \
    | head -1
}

emit_field() { # <var-name> <field-name>
  local id
  id=$(field_id "$2")
  if [ -z "$id" ]; then
    missing+=("$2 field")
    echo "$1=  # not found - fill in by hand, or drop if unused"
  else
    echo "$1=$id"
  fi
}

emit_option() { # <key> <field-name> <option-name>
  local id
  id=$(option_id "$2" "$3")
  if [ -z "$id" ]; then
    missing+=("$2 / $3 option")
    echo "  [$1]=  # not found"
  else
    echo "  [$1]=$id"
  fi
}

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by init-config.sh for project $project_num (owner: $owner)."
  echo "# Review before use - anything marked 'not found' didn't match by"
  echo "# name and needs a manual look at refresh-ids.sh's output, or"
  echo "# should be deleted along with its usages if this project has no"
  echo "# such field (see SKILL.md)."
  echo
  echo "PROJECT_KEY=$project_key"
  echo "PROJECT_NUM=$project_num"
  echo "OWNER=$owner"
  echo "PROJECT_ID=$project_id"
  echo
  emit_field STATUS_FIELD Status
  emit_field TYPE_FIELD Type
  emit_field EFFORT_FIELD Effort
  emit_field EPIC_FIELD Epic
  echo
  echo "declare -A STATUS=("
  emit_option backlog Status Backlog
  emit_option ready Status Ready
  emit_option blocked Status Blocked
  emit_option in_progress Status "In Progress"
  emit_option "done" Status Done
  echo ")"
  echo "declare -A TYPE=("
  emit_option story Type Story
  emit_option bug Type Bug
  emit_option task Type Task
  emit_option spike Type Spike
  emit_option epic Type Epic
  echo ")"
  echo "declare -A EFFORT=("
  emit_option xs Effort XS
  emit_option s Effort S
  emit_option m Effort M
  emit_option l Effort L
  emit_option xl Effort XL
  emit_option xxl Effort XXL
  echo ")"
} > "$conf"

echo "Wrote $conf" >&2
if [ "${#missing[@]}" -gt 0 ]; then
  echo "Not auto-resolved, review by hand:" >&2
  printf '  - %s\n' "${missing[@]}" >&2
fi
